services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Letkode\LocaleBundle\:
        resource: '../src/'
        exclude:
            - '../src/LetkodeLocaleBundle.php'
            - '../src/DependencyInjection/'
            - '../src/LocaleListener.php'

    Letkode\LocaleBundle\LocaleListener:
        tags:
            - name: kernel.event_listener
              event: kernel.request
              method: onKernelRequest
              priority: '%letkode.locale.listener_priority%'
